config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#top'
  get '/thanks' => 'home#thanks'
  
  get '/collection' => 'works#collection'
  resources :works, only: [:new, :index, :edit, :create, :destroy, :update]
  post 'login' => 'admins#sign_in'
  post 'logout' => 'admins#sign_out'
  get '/login' => 'admins#admin_form'
  post '/ja' => 'home#to_ja'
  post '/en' => 'home#to_en'
  post '/send_jp' => 'home#send_jp'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  validates :name, {presence: true}
  validates :mail, {presence: true, uniqueness: true}
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, {presence: true}
  validates :image, {presence: true}
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def admin_form
  end

  def sign_in
    @admin = Admin.find_by(mail: secure_params[:mail])
    respond_to do |format|
      if @admin && @admin.authenticate(secure_params[:password])
        session[:admin_user] = @admin.name
        session[:admin_id] = @admin.id
        format.html {redirect_to collection_path, notice: "ログインしました"}
      else
        @error_message = "メールアドレスまたはパスワードが間違っています"
        format.html {render :admin_form, status: :unprocessable_entity}
      end
    end
  end

  def sign_out
    session.delete(:admin_user)
    session.delete(:admin_id)
    flash[:notice] = "ログアウトしました"
    redirect_to "/login"
  end

private

  def secure_params
    params.require(:admin).permit(:password, :mail)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :admin_exist
  
  def author_session
    if session[:admin_user] == nil
      flash[:notice] = "権限がありません"
      redirect_to "/"
    end
  end

  private

  def session_check
    if session[:admin_user] != "licht"
      session[:admin_user] = nil
      session[:admin_id] = nil
    end
  end

  def admin_exist
    if session[:admin_user]
      @admin_exist = "exist"
    else
      @admin_exist = nil
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    works = Work.all.order(id: :desc)
    @three_works = works.first(3)
    @contact = Contact.new
  end

  def thanks
  end

  def send_jp
    contact = Contact.new(sender_params)
    ContactMailer.send_mail(contact).deliver_now
    ContactMailer.to_admin(contact).deliver_now
    respond_to do |format|
      format.html {redirect_to thanks_path, notice: "送信しました"}
    end
  end

  def to_jp
    I18n.lacale = :ja
    redirect_to request.referer
  end

  def to_en
    I18n.locale = :en
    redirect_to request.referer
  end

  private

  def sender_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  before_action: :session_check
  before_action: :author_session

  def new
    @work = Work.new
  end

  def index
    @works = Work.all.order(created_at: :desc)
  end

  def create
    @work = Work.new(user_id: session[:admin_id])
    @work.save
      if params[:image]
        @work.image_name = "#{@work.id}.jpg"
        image = params[:image]
        file.binwrite("public/work_images/#{@work.image_name}, image.read")
      else
        @work.destroy
        render("works/new")
      end

      if @work.save
        flash[:notice] = "画像をアップロードしました"
        redirect_to("/collection")
      else
        render("works/new")
      end
  end

  def edit
    @work = Work.find_by(id: params[:id])
  end

  def update
    @work = Work.find_by(id: params[:id])
    image = params[:image]
    file.binwrite("public/work_images/#{@work.image_name}, image.read")
    @work.save
    flash[:notice] = "画像を更新しました"
    redirect_to("/collection")
  end

  def destroy
    @work = Work.find_by(id: params[:id])
    flash[:notice] = "削除に成功しました"
    @work.destroy
    redirect_to("/collection")
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :session_check
  before_action :author_session, {only: [:new, :index, :create, :edit, :update, :destroy]}

  def collection
    @works = Work.all.reverse_order.page(params[:page]).per(10)
  end
  
  def new
    @work = Work.new
  end

  def index
    @works = Work.all.reverse_order.page(params[:page]).per(30)
  end

  def create
    @work = Work.new(work_params)
    @work.user_id = session[:admin_id]
    respond_to do |format|
      if @work.save
        format.html {redirect_to works_path, notice: "画像をアップロードしました"}
      else
        @error_message = "保存できませんでした"
        format.html {render :new, status: :unprocessable_entity}
      end
    end
  end

  def edit
    @work = Work.find_by(id: params[:id])
  end

  def update
    @work = Work.find_by(id: params[:id])
    respond_to do |format|
      if @work.update(work_params)
        format.html {redirect_to works_path, notice: "更新しました"}
      else
        @error_message = "保存できませんでした"
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @work = Work.find_by(id: params[:id])
    @work.destroy
    respond_to do |format|
      format.html {redirect_to works_path, notice: "削除に成功しました", status: :see_other } 
    end
  end

  private

  def work_params
    params.require(:work).permit(:title, :link_url, :image, :user_id)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/admin_form.html.erb
<div class="admin_login">
  <div class="login_form">
    <% if @error_message %>
      <div class="form-error">
        <%= @error_message %>
      </div>
    <% end %>
    <%= form_with url: "/login", data: {turbo_method: :post}, local: true do |form| %>
      <h2>Login</h2>
      <%= form.text_field :mail, class: "form-control", placeholder: "メールアドレス" %>
      <%= form.password_field :password, class: "form-control", placeholder: "パスワード" %> 
      <%= form.submit :Login, class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/admins/admin_form.html.erb
<div class="admin_login">
  <% if @error_message %>
    <div class="form-error">
      <%= @error_message %>
    </div>
  <% end %>
  <div class="login_form">
    <%= form_with url: "/login",scope: :admin, data: {turbo_method: :post}, local: true do |form| %>
      <h2>Login</h2>
      <%= form.text_field :mail, class: "form-control", placeholder: "メールアドレス" %>
      <%= form.password_field :password, class: "form-control", placeholder: "パスワード" %> 
      <%= form.submit :submit, class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/home/collection.html.erb
<div class="collection-container">
  <% @works.each do |work| %>
    <div class="work-content">
      <div class="work">
        <%= image_tag work.image.url %>
        <% if work.link_url %>
          <div class="link-box">
            <%= link_to("#{work.link_url}", class:"site-btn" ) do %>
              <span>Visit page</span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= paginate @works %>
</div>

app/views/home/thanks.html.erb
<h2>Thank you for mailing</h2>

app/views/home/top.html.erb
<div class="top-container">
  <div class="visual-container">
    <div id="main-visual">
      <div class="visual-navi">
        <ul>
          <%= render 'layouts/navigation' %>
        </ul>
      </div>
    </div>
  </div>
  <div id="about">
    <div class="description">
      <div class="text-area">
        <h2>About Me</h2>
        <p>『モノづくり』に興味を持つようになったのは、ドイツに２年間住んでいた経験から。<br>
            アパレル店舗の運営に携わりながら、テーラーで服飾とファッションデザインについて修行しました。<br>
            ２０１９年からは同時並行でプログラミングの勉強、および、ロゴのデザイン作成を開始。<br>
            現在は、フリーランスとして、デジタルデザイナーとデベロッパーとして活動しています。</p>
        <table>
          <thead><tr><td colspan="2"></td></tr><thead>
          <tbody>
            <tr>
              <td>言語</td><td>HTML/CSS, Sass, Ruby, Rails, Javascript, jQuery, python, GAS</td>
            <tr>
            <tr>
              <td>ツール</td><td>Illustrator, Photoshop, Affinity</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="about-image">
      <img src="/visual_image/pf_about.png">
    </div>
  </div>
  <div id="works">
    <div class="work-text">
      <h2>Works</h2>
    </div>
    <% @three_works.each do |work| %>
      <div class="work-container">
        <%= image_tag work.image.url %>
        <% if work.link_url %>
          <div class="url-link">
            <%= link_to("#{work.link_url}", id:"site-btn") do %>
              <span>Visit page</span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="to_collection">
      <%= link_to("/collection") do %>
        <div id="btn">
          <span>more works<span>
        </div>
      <% end %>
    </div>
  </div>
  <div id="contact">
    <div class="contact-content">
      <div class="contact-text">
        <h2>Contact</h2>
      </div>
      <div class="contact-form">
      <%= form_with url: send_jp_path, scope: :contact, data: {turbo_method: :post}, local: true do |f| %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        <%= f.text_field :email, class: "form-control", placeholder: "E-mail" %>
        <%= f.text_area :message, class: "form-control", id: "form-area" %>
        <%= f.submit :send, id: "submit-btn"%>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<% if @admin_exist %>
  <li>
    <%= link_to("MGT." ,"/works", id: "btn") %>
  </li>
  <li>
    <%= link_to("/logout", data: {turbo_method: :post}) do %>
      <span id="btn">Logout</span>
    <% end %>
  </li>
<% else %>
  <li><a href="/#works" id="btn">Works</a></li>
  <li><a href="/#about" id="btn">About</a></li>
  <li><a href="/#contact" id="btn">Contact</a></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="uft-8">
    <title>Haruki's portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="ポートフォリオです。">
    <meta name="keyword" content="油井　陽輝 Haruki Yui Portfolio Webdesigner Developer ウェブデザイナー　開発者　ポートフォリオ">
    <meta name="author" content="油井 陽輝">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <div class="header-container">
      <div id="logo">
        <%= link_to(image_tag("/visual_image/Haruki_logo.png"), "/") %>
      </div>
      <div class="header-navi">
        <ul>
          <%= render 'layouts/navigation' %>
          <li>
            <%= link_to("/collection") do %>
              <p id="btn">Collection</p>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="lang-navi">
        <ul>
          <li>
            <%= link_to("/en", data: {turbo_method: :post, turbo_confirm: 'Are you sure to switch to English?'}) do %>
              <span class="lang-btn">English</span>
            <% end %>
          </li>
          <li>
            <%= link_to("/ja", data: {turbo_method: :post, turbo_confirm: '日本語に切り替えますか'}) do %>
              <span class="lang-btn">日本語</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </header>
  <main>
      <% if flash[:notice] %>
        <div id="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
    <%= yield %>
  </main>
  <footer>
    <div id="copyright">
      <p>Copyright🄫All reserved by Haruki Yui</p>
    </div>
  </footer>
  </body>
</html>

app/views/work/index.html.erb
<div class="index-container">
  <div class="new">
    <%= link_to("/works/new") do %>
      <span id="btn">新規投稿</span>
    <% end %>
  </div>
  <table>
    <tr>
      <th>Title</th>
      <th>作成日</th>
      <th>画像</th>
      <th></th>
    </tr>
    <% @works.each do |work| %>
    <tr>
      <td><%= work.title %></td>
      <td><%= work.created_at %></td>
      <td><img src="<%= "/work_images/#{work.image_name}" %>"></td>
      <td>
        <% if work.user_id == session[:admin_id].to_i %>
          <%= link_to("edit","/works/#{work.id}/edit") %>
          <%= link_to("delete","/works/#{work.id}/destroy", data {turbo_method: :delete, turbo_confirm: '削除してよろしいですか') %>
        <% end %>
      </td>
    </tr>
    <% end %>
    <%= paginate @works %>
  </table>
</div>

app/views/works/_form.html.erb
<div class="edit-page">
  <% if @error_message %>
    <div class="form-error">
      <%= @error_message %>
    </div>
  <% end %>
  <div class="work-form">
    <%= form_with(url: path, scope: :work, model: work , local: true, data: {turbo_method: method}) do |f| %>
      <h2><%= tag %></h2>
      <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
      <label id="upload">
        画像をアップロード
        <%= f.file_field :image, style:"display: none;" %>
      </label>
      <%= f.text_field :link_url, placeholder: "URLを入力", class: "form-control" %>
      <%= f.submit :submit, id: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/works/collection.html.erb
<div class="collection-container">
  <% @works.each do |work| %>
    <div class="work-content">
      <div class="work">
        <%= image_tag work.image.url %>
        <% if work.link_url %>
          <div class="link-box">
            <%= link_to("#{work.link_url}", id:"site-btn" ) do %>
              <span>Visit page</span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= paginate @works %>
</div>

app/views/works/edit.html.erb
<%= render 'works/form', path: work_path, work: @work, method: :patch, tag: "編集"%>

app/views/works/index.html.erb
<div class="index-container">
  <div class="new-btn-container">
    <div class="new">
      <%= link_to("新規投稿", "/works/new", class: "new-btn") %>
    </div>
  </div>
  <table class="work-list">
    <thead>
      <tr>
        <th>Title</th>
        <th>作成日</th>
        <th>サイトURL</th>
        <th>画像</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @works.each do |work| %>
    <tbody>
      <tr>
        <td><%= work.title %></td>
        <td><%= l work.created_at , format: :long %></td>
        <td><%= link_to("#{work.link_url}") %></td>
        <td><%= image_tag work.image.url, class: "image-index" %></td>
          <% if work.user_id == session[:admin_id].to_i %>
            <td><%= link_to("edit","/works/#{work.id}/edit", class: "edit-btn edit") %></td>
            <td><%= link_to("delete",work_path(work.id) ,class: "edit-btn delete", data: {turbo_method: :delete, turbo_confirm: '削除してよろしいですか'}) %></td>
          <% end %>
      </tr>
    </tbody>
    <% end %>
    <%= paginate @works %>
  </table>
</div>

app/views/works/new.html.erb
<%= render 'works/form', path: works_path, work: @work, method: :post, tag: "新規登録"%>